### ISSUE TITLE
Where is the css?

### ISSUE THREAD

**Issue by sandrocsimas** [aitboudad/ngx-loading-bar#100]
In the NPM module page it's mentioning a css file, but I can't find it. I'm using webpack.

**Comment by aitboudad** [comment]
it's an old version, css has been moved into the component itself so you don't have to import it anymore.

can you provide me the link that were mentioned ?

**Comment by sandrocsimas** [comment]
Sorry @aitboudad, I'm not finding the page, maybe I was looking at the wrong module.
The loading bar is working here now. I will close the issue.
