### ISSUE TITLE
FR: Disable loading progress on server side for better render speed

### ISSUE THREAD

**Issue by clarkorz** [aitboudad/ngx-loading-bar#102]
I'm trying to use `ngx-loading-bar` in an angular universal project. But I found that the render time is very long, about 500ms to 1s+ when there are a few async requests. If I remove `ngx-loading-bar` entirely, render time speeds up to 20ms.

I think loading bar is a nice thing in client side, but not in server side (since it uses many `setTimeout`). It's better to disable the progress on server side.

**Comment by aitboudad** [comment]
that make sense, fixed in `2.2.0`

**Comment by clarkorz** [comment]
Confirm, it works~
