### ISSUE TITLE
Support for Angular 7 and IvyRenderer

### ISSUE THREAD

**Issue by anth-git** [aitboudad/ngx-loading-bar#107]
If I try to use ngx-loading-bar with Angular 7 and ivy renderer enabled, I get an error:

```
ERROR in : Template parse errors:
The pipe 'async' could not be found ("
    <ng-container *ngIf="(value !== null ? v[ERROR ->]alue : loader.progress$|async) as progress">
      <div id="loading-bar-spinner" *ngIf="includeSpinne"): <proj_path>/node_modules/@ngx-loading-bar/core/ngx-loading-bar-core.d.ts.LoadingBarComponent.html@1:44
```

Since Angular 7 is out, and IvyRenderer is 93% ready (https://is-angular-ivy-ready.firebaseapp.com/#/status) component should support Angular7 & new renderer.

**Comment by aitboudad** [comment]
v7 is already supported but ivy is not ready yet
