### ISSUE TITLE
progress bar not showing up

### ISSUE THREAD

**Issue by ssprajput** [aitboudad/ngx-loading-bar#110]
I have this angular 7 app that uses SP PNP libraries which in turn makes all the service requests (HTTPClient) I implemented this package as per instructions hoping it would intercept all the requests and I implemented both (HTTP and HTTPClient modules) but nothing shows up on the screen. Am I missing any configuration for intercepting? Instructions were very simple. I put the <ngx-loading-bar [color]="'blue'"></ngx-loading-bar> in multiple places including app component HTML. I do not want to manually load this so I didn't do anything stated in that section.

**Comment by aitboudad** [comment]
I'm not sure what `SP PNP libraries` does but you may check my answer about ngx-restangular https://github.com/aitboudad/ngx-loading-bar/issues/96#issuecomment-406860166

**Comment by ssprajput** [comment]
I do not use Restangular. Though the SP PNP also makes rest calls to get/post data.
https://github.com/pnp/pnpjs

Not sure if that restangular code is relevant here.

**Comment by aitboudad** [comment]
if I clearly understood you've used `pnpjs` lib for making http calls instead of angular http client lib, right?
if so then you just need to check if `pnpjs` provide a global hook similar to angular http interceptor and apply my suggestion about Restangular.

**Comment by ssprajput** [comment]
Got it. So an interceptor in my project wouldn't intercept the call, it has to be in pnpjs library, right?

**Comment by aitboudad** [comment]
yep
