### ISSUE TITLE
More than one component matched on this element

### ISSUE THREAD

**Issue by hanijazzar** [aitboudad/ngx-loading-bar#111]
I'm trying to implment Github behavior in loading. When a user clicks to go to a new route, I need to show the loading bar, get all the data, then navigate the user to the new route with all the data loaded through the http client. Any ideas how to implement that? I tried imprting both LoadingBarHttpClientModule and  LoadingBarRouterModule but got the error "More than one component matched on this element."

      
    imports: [
      BrowserModule,
      HttpClientModule,
      AppRoutingModule,
      LoadingBarHttpClientModule,
      LoadingBarRouterModule,
    ],
        

Error in console: "More than one component matched on this element."

**Comment by aitboudad** [comment]
could you please check the installed version of `ngx-loading-bar` packages match the same version?
also, you may try to move (LoadingBarHttpClientModule, LoadingBarRouterModule) into the main module instead of child one.

**Comment by hanijazzar** [comment]
Still same issue. Let's say it works, will I get github loading behavior? Or that requires route resolver?

**Comment by aitboudad** [comment]
can show me the output of the following cmd: `npm ls @ngx-loading-bar/core`

**Comment by hanijazzar** [comment]
├─┬ @ngx-loading-bar/http-client@3.0.0
│ └── @ngx-loading-bar/core@3.0.0 
└─┬ @ngx-loading-bar/router@3.0.0
  └── @ngx-loading-bar/core@3.0.0

**Comment by aitboudad** [comment]
for me I get:
```ts
├─┬ @ngx-loading-bar/http-client@3.0.0
│ └── @ngx-loading-bar/core@3.0.0
└─┬ @ngx-loading-bar/router@3.0.0
  └── @ngx-loading-bar/core@3.0.0  deduped
```

try to remove `@ngx-loading-bar/core` in your `package.json` if exist and then try `npm install` again after removing `node_modules` folder and `package-lock.json` file to see if it can solve that issue.

**Comment by hanijazzar** [comment]
Alright thanks I will try that. But do you know if having both gives the github loading behavior? Or that requires route resolver?

**Comment by aitboudad** [comment]
I think it can work without resolver because the `http-client` will trigger the loading-bar when data is being loading

**Comment by aitboudad** [comment]
I've published a `v4` which would solve having duplicated dependency of `@ngx-loading-bar/core` see the [CHANGELOG](https://github.com/aitboudad/ngx-loading-bar/blob/master/CHANGELOG.md#breaking-changes)

**Comment by hanijazzar** [comment]
Okay great thank you!
