### ISSUE TITLE
Multiple Positioning

### ISSUE THREAD

**Issue by Exocomp** [aitboudad/ngx-loading-bar#120]
I would like to have different positions for the loader depending on the page the user visits.

For AppComponent the default top position is fine.  As the user visits the main site I would like the loader to be positioned just below the site header.

How can I accomplish this with a single instance of the loader on the DOM?

I tried working with setting [fixed]="false" and then changing the position of the loader with css but didn't have much luck so just reaching out to see how you would recommend setting it up.

**Comment by Exocomp** [comment]
I got a solution I'm happy with by selectively loading  ngx-loading-bar on the DOM using [fixed]="false" and without where needed.  It's a bit of extra logic but if there is an easier way with just using css and a single instance on the DOM that would be nice.

**Comment by aitboudad** [comment]
well, I think applying custom CSS should do the job, could you please replicate what you've done using the following starter example https://stackblitz.com/edit/angular-qmotfh in order to see if there is a better or an alternative way.
