### ISSUE TITLE
Is it possible to differentiate the reason why the loading bar is showing? (HttpClient or Router)

### ISSUE THREAD

**Issue by wwarby** [aitboudad/ngx-loading-bar#121]
What I'd really like to do is show the loading bar when an HttpClient request is being made, and a full page darkening overlay with a spinner when the router is routing to a new page. It's relatively easy with ngx-loading-bar to do one or the other (the latter using a custom component that consumes `LoadingBarService.progress$`) but I see no properties that would enable me to discriminate the reason the loading bar is being shown. Is that possible?

**Comment by aitboudad** [comment]
> Is that possible?

not possible right now but seems to be a valid request that should be implemented, I'll check it tomorrow.

**Comment by aitboudad** [comment]
Added in `5.0.0-alpha.0` release, which allows controlling a specific loading bar instance:

- using `LoadingBarService`:

```ts
// select the router loader instance
const state = this.loadingBar.useRef('router');

// control state
state.start();
state.complete();

// get the progress value
const value$ = state.value$;
```

- passing `ref` input to the `ngx-loading-bar` component:

```html
<!-- loading bar for router -->
<ngx-loading-bar ref="router"></ngx-loading-bar>

<!-- loading bar for http -->
<ngx-loading-bar ref="http"></ngx-loading-bar>
```
