### ISSUE TITLE
Expose the loading state

### ISSUE THREAD

**Issue by leye0** [aitboudad/ngx-loading-bar#126]
get isLoading(): boolean {
      // The ngx-loading-bar plugin doesn't expose the loading state
      return (this.loadingBarService as any)._pendingRequests > 0;
    }

I currently have to 'hack' into the private `LoadingBarService` properties to bind to the state of the loading bar. I want to re-use the `LoadingBarService` state to enable and disable my buttons. Could there be this kind of property exposed in the service?

**Comment by aitboudad** [comment]
Try with:
```ts
@Component({
  selector: 'app',
  template: `
    ...
    <button [disabled]="isLoading$|async"><button>
  `,
})
export class App {
  isLoading$ = this.loadingBarService.progress$.pipe(
    map(value => value > 0),
  );
}
```
