### ISSUE TITLE
Infinite loading when using zero-configuration mode

### ISSUE THREAD

**Issue by rangitha** [aitboudad/ngx-loading-bar#129]
When using ngx-loading-bar for http-client requests, the loading bar starts on application load and never completes. However I can manually start and complete the bar without issue if I'm only using the core module.

I can see the following pending request that angular-cli initiates:

<img width="645" alt="websockets" src="https://user-images.githubusercontent.com/3658618/59927691-afdd6380-945a-11e9-93c7-0d83bbe968f4.PNG">

I only have one HTTP interceptor that adds an authorization token header. However, interceptors don't seem to pick-up the above request.

I'm using the following versions: 

- @angular/platform-browser: ~7.1.0
- @angular/cli: ^7.1.0
- @ngx-loading-bar/core: ^4.2.0
- @ngx-loading-bar/http-client: ^4.2.0

And I've the following two imports in the AppModule:

- LoadingBarModule,
- LoadingBarHttpClientModule,

Maybe I'm doing something wrong because I can't see any issues logged along these lines.

**Comment by aitboudad** [comment]
not sure what's going wrong :thinking:, a reproduction example is needed.

> I only have one HTTP interceptor that adds an authorization token header. 

can you disable that interceptor and check again.

**Comment by rangitha** [comment]
That did the trick! It's resolved now, but what do you think is wrong with Version 1 below: 

**Version 1 (asynchronous):**
```
export class AuthInterceptor implements HttpInterceptor {
  constructor(
    private authService: AuthService
  ) { }

  intercept(request: HttpRequest<any>, next: HttpHandler) {
    let headers = request.headers || new HttpHeaders();

    return this.authService.getAuthorizationToken().pipe(
      mergeMap((authToken) => {
        headers = headers.append('Authorization', authToken);

        return next.handle(request.clone({ headers }));
      })
    );
  }
}
```

**Version 2 (synchronous):**
```
export class AuthInterceptor implements HttpInterceptor {
  private authToken: string;

  constructor(private authService: AuthService) {
    this.authService.getAuthorizationToken().subscribe((authToken) => {
      this.authToken = authToken;
    });
  }

  intercept(request: HttpRequest<any>, next: HttpHandler) {
    let headers = request.headers || new HttpHeaders();
    headers = headers.append('Authorization', this.authToken);

    return next.handle(request.clone({ headers }));
  }
}
```

**Comment by aitboudad** [comment]
Normally the first version is the right one, I'll check it to see what's going wrong there.

**Comment by aitboudad** [comment]
test on my side and I didn't notice any issue, the wrong part is located in your `AuthInterceptor` which should skip `AuthorizationToken` request to avoid a recursive Http call:

```patch
intercept(request: HttpRequest<any>, next: HttpHandler) {
  let headers = request.headers || new HttpHeaders();
++  if (headers.has('Authorization') || request.url === 'your_authorization_token_url') {
++    return next.handle(request);
++  }

  return this.authService.getAuthorizationToken().pipe(
    mergeMap(() => {
      headers = headers.append('Authorization', 'authToken');

      return next.handle(request.clone({ headers }));
    })
  );
}
```
