### ISSUE TITLE
IVY Support.

### ISSUE THREAD

**Issue by hannandesai** [aitboudad/ngx-loading-bar#130]
Can you please tell me when this will be IVY ready? As version 8 of angular supports IVY.

**Comment by aitboudad** [comment]
Just tested with IVY on my side and I didn't notice any issue 🎉🎉🎉!

**Comment by huineng** [comment]
using angular 8.2 and running the ivy compiler

"./node_modules/.bin/ivy-ngcc"

i get 

```
Compiling @ngx-loading-bar/core : es2015 as esm2015
Compiling @ngx-loading-bar/core : main as umd
Compiling @ngx-loading-bar/core : module as esm5
Compiling @ngx-loading-bar/http-client : es2015 as esm2015
Compiling @ngx-loading-bar/http-client : main as umd
Value at position 1 in the NgModule.imports of LoadingBarHttpClientModule is not a reference: [object Object]
```

**Comment by aitboudad** [comment]
Hi @huineng,
`v8` isn't fully compatible with `ivy` so instead, you may try with the next v9 (which will be released soon). 
check: https://next.angular.io/guide/updating-to-version-9
