### ISSUE TITLE
[docs] improvement about lazy loading

### ISSUE THREAD

**Issue by borriej** [aitboudad/ngx-loading-bar#136]
Hi!

Love the module. I was struggling a bit with lazyLoading and getting the loader to start when the module is being loaded. I turns out you need ```LoadingBarRouterModule``` to show a loader when a lazy loaded module is being loaded. I was only using ```LoadingBarHttpClientModule```. 

Maybe this can be added to the docs: 

If you're using Lazy Loaded Modules in your app, please use ```LoadingBarRouterModule```, because although a request is being fired in the nework console to fetch the js file, it won't trigger the ```LoadingBarHttpClientModule```.

Im using both ```LoadingBarHttpClientModule``` & ```LoadingBarRouterModule``` at the moment.

**Comment by aitboudad** [comment]
can you update Readme with those changes, and send a PR?

**Comment by borriej** [comment]
done!
