### ISSUE TITLE
[docs] remove forRoot()

### ISSUE THREAD

**Issue by borriej** [aitboudad/ngx-loading-bar#137]
Hi, 

forRoot() has been removed (https://github.com/aitboudad/ngx-loading-bar/pull/112) but, it's still in the readme?

```
    // for Core use:
    // LoadingBarModule.forRoot()
```

im getting an error:
```
Property 'forRoot' does not exist on type 'typeof LoadingBarModule'
```

How do we add loading bar to a Core Module?
Maybe remove forRoot() from the readme docs?

**Comment by aitboudad** [comment]
> How do we add loading bar to a Core Module?

`LoadingBarModule`  without `forRoot `.

> Maybe remove forRoot() from the readme docs?

fixed, thanks!
