### ISSUE TITLE
Prevent the bar from going back to zero when there're multiple HTTP calls

### ISSUE THREAD

**Issue by AmirSavand** [aitboudad/ngx-loading-bar#142]
In some pages, there are multiple API calls to back-end and the loading bar keeps going back and completes itself again.

This is ok however I want a way to change this behavior.

Only 1 bar for multiple requests. Even if I could ignore the rest while the first one exists.

**Comment by aitboudad** [comment]
see https://github.com/aitboudad/ngx-loading-bar/issues/30#issuecomment-379047083

**Comment by AmirSavand** [comment]
I did the exact thing but still happening, the progress bar goes back to starts again when the previous one was not completed yet.

Is there another way? Otherwise, the only way would be going to every component and use manual start/stop.

**Comment by aitboudad** [comment]
could you please try the following fix: https://stackblitz.com/edit/angular-mv9bgj

**Comment by AmirSavand** [comment]
Not a perfect solution but it works. Thanks.

**Comment by aitboudad** [comment]
fixed in `5.0.0-alpha.1`, the workaround can be removed.
