### ISSUE TITLE
Progress bar not showing up in AOT prod build

### ISSUE THREAD

**Issue by Sonik20** [aitboudad/ngx-loading-bar#146]
Progress bar shows up with normal build but not with AOT prod build.

Here is my package.json :
    "@angular/animations": "^7.2.9",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "7.2.9",
    "@angular/compiler": "7.2.9",
    "@angular/core": "7.2.9",
    "@angular/forms": "7.2.9",
    "@angular/http": "7.2.9",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/http-client": "^1.6.0"

Please share your suggestions @aitboudad

**Comment by aitboudad** [comment]
the  `@ngx-loading-bar/http-client`  version should be the same as `@ngx-loading-bar/core` which is `4.2.0`.

```patch
-- "@ngx-loading-bar/http-client": "^1.6.0"
++ "@ngx-loading-bar/http-client": "^4.2.0"
```

**Comment by Sonik20** [comment]
Thanks @aitboudad
