### ISSUE TITLE
Authorization interceptor header

### ISSUE THREAD

**Issue by mrahla** [aitboudad/ngx-loading-bar#147]
I am using token based auth. When using the loading bar module it removes the authorization header
My interceptor:
`request.clone({
            setHeaders: {
                'Authorization': `Bearer ${token}`
            }
        });`

**Comment by aitboudad** [comment]
not true, the defined headers should remains 🤔, here is our interceptor: https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/http-client/src/loading-bar.interceptor.ts#L14

I'm using an `Authorization` in my app and I didn't notice such behavior, so I think I may need a reproduction example in that case 🙏.

**Comment by mrahla** [comment]
Full interceptor:

`import { Injectable } from '@angular/core';
import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor, HttpErrorResponse } from '@angular/common/http';
//import { AuthService } from './services/auth.service';
import { Observable, throwError, BehaviorSubject, of } from 'rxjs';
import { catchError, filter, take, switchMap } from 'rxjs/operators';
import { UserApiService } from '@services/user-api.service';

@Injectable()
export class UnauthorizedInterceptor implements HttpInterceptor {

    private isRefreshing = false;
    private refreshTokenSubject: BehaviorSubject<any> = new BehaviorSubject<any>(null);

    constructor(public authService: UserApiService) { }

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

        if (this.authService.accessToken) {
            request = this.addToken(request, this.authService.accessToken);
        }

        return next.handle(request).pipe(catchError(error => {
            if (error instanceof HttpErrorResponse) {
                if (error.status === 401) {
                    return this.handle401Error(request, next);
                }
                if (error.status === 400 && request.headers.has("token-expired")) {
                    this.authService.logout();
                    this.authService.redirectForLogin();
                    return next.handle(request);
                }
            }
            //else {
            return throwError(error);
            //}
        }));
    }

    private addToken(request: HttpRequest<any>, token: string) {
        return request.clone({
            setHeaders: {
                'Authorization': `Bearer ${token}`
            }
        });
    }

    private handle401Error(request: HttpRequest<any>, next: HttpHandler) {
        if (!this.isRefreshing) {
            this.isRefreshing = true;
            this.refreshTokenSubject.next(null);

            return this.authService.updateToken().pipe(
                switchMap((token: any) => {
                    this.isRefreshing = false;
                    this.refreshTokenSubject.next(token.token);
                    return next.handle(this.addToken(request, token.token));
                }));

        } else {
            return this.refreshTokenSubject.pipe(
                filter(token => token != null),
                take(1),
                switchMap(jwt => {
                    return next.handle(this.addToken(request, jwt));
                })
            );
        }
    }
}`

**Comment by mrahla** [comment]
> not true, the defined headers should remains 🤔, here is our interceptor: https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/http-client/src/loading-bar.interceptor.ts#L14
> 
> I'm using an `Authorization` in my app and I didn't notice such behavior, so I think I may need a reproduction example in that case 🙏.

I have 2 modules. The main module has interceptors, while the secondary module uses the loading bar. maybe its related?

**Comment by aitboudad** [comment]
here is a working example https://stackblitz.com/edit/angular-wchdrb, please try to edit it and provide me a reproduction example.

**Comment by arnaudgibert** [comment]
For future references. I had the same issue and I resolved it by making 2 changes. 

- import from app.module.ts instead of a parent module 
- import this modules before importing the module containing my other HttpInterceptors

I hope it will help...

**Comment by progtarek** [comment]
I had the same issue and I used @arnaudgibert  solution and it works for me.
