### ISSUE TITLE
How to manually remove ngx-loading-bar from the DOM ?

### ISSUE THREAD

**Issue by bitf12m512** [aitboudad/ngx-loading-bar#149]
I want to remove the loading bar from DOM manually once it's completed.
It get's removed after a certain amount of time but I wanna remove it as soon it is completed.

Need some help on it.

**Comment by aitboudad** [comment]
use `ngIf`:

```ts
@Component({
  selector: 'app-root',
  template: `
    <ng-container *ngIf="loader.progress$|async as value">
      <ngx-loading-bar [value]="value"></ngx-loading-bar>
    <ng-container>
  `,
})
export class AppComponent {
  constructor(public loader: LoadingBarService) { }
}
```

**Comment by bitf12m512** [comment]
> use `ngIf`:
> 
> ```ts
> @Component({
>   selector: 'app-root',
>   template: `
>     <ng-container *ngIf="loader.progress$|async as value">
>       <ngx-loading-bar [value]="value"></ngx-loading-bar>
>     <ng-container>
>   `,
> })
> export class AppComponent {
>   constructor(public loader: LoadingBarService) { }
> }
> ```
That's not a proper solution, let's say I am using it at 50 different pages I have to use ngIf at every page which is not an ideal solution.
Anything else you would suggest?

**Comment by aitboudad** [comment]
> Anything else you would suggest?

As far as I know that's the only way (if I clearly understood the request), the purpose of `ngx-loading-bar` is to be placed in the root component and not to be duplicated in 50 different pages.

`Note`: you may create another component that wraps the above proposal but the created component selector will be present in the dom.

**Comment by bitf12m512** [comment]
I understand the fact that in the Web Application I can add it in the
Header Complement which is common in the application and "ngIf" will do the
job. But what if I am using it in an IONIC based Mobile Application.
I mean when we do .destroy or .dismiss shouldn't it automatically get
hidden?

Thanks

**Comment by aitboudad** [comment]
well I don't have much knowledge in IONIC but I would say `ngx-loading-bar` is not required to use you can rely on [ion-progress-bar](https://ionicframework.com/docs/api/progress-bar):

```ts
@Component({
  selector: 'app-root',
  template: `
    <ng-container *ngIf="loader.progress$|async as value">
      <ion-progress-bar ...></ion-progress-bar>
    <ng-container>
  `,
})
export class AppComponent {
  constructor(public loader: LoadingBarService) { }
}
```
