### ISSUE TITLE
Angular 9 Ivy - Bar does not seem to work

### ISSUE THREAD

**Issue by ninjavis** [aitboudad/ngx-loading-bar#154]
Firstly, thank you for creating this! Really appreciate the effort.

I'm not sure if you're aware of this module's incompatibility with Angular 9 Ivy.

Here's my compilation errors for your reference. Would really appreciate it if you could have a look at it please. Thank you so much!

`ERROR in node_modules/@ngx-loading-bar/http-client/http.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@ngx-loading-bar/http-client) which declares LoadingBarHttpClientModule has not been processed correctly by ngcc, or isnot compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class LoadingBarHttpClientModule {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@ngx-loading-bar/router/router.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@ngx-loading-bar/router) which declaresLoadingBarRouterModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if thelibrary is expected to be compatible with Ivy.

    3 export declare class LoadingBarRouterModule {
                           ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@ngx-loading-bar/core/core.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@ngx-loading-bar/core) which declares LoadingBarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the libraryis expected to be compatible with Ivy.

    1 export declare class LoadingBarModule`

**Comment by aitboudad** [comment]
The latest time I've checked seems working as expected so I'd suggest first to ensure you're using the latest version of Angular and if it didn't work you may try the `5.0.0-alpha.1` version of `ngx-loading-bar`.

**Comment by aitboudad** [comment]
Probably related to https://github.com/aitboudad/ngx-loading-bar/issues/151#issuecomment-592382876

**Comment by ninjavis** [comment]
Thank you, I have the same feeling. I installed a different plugin, but realised that "ng serve" was displaying the same problem for the new plugin.

So what solved it for me was to stop 'ng serve' and restart it, lol! Silly, but as we know, all software might have bugs :)

Thanks for your quick response, appreciate it!
