### ISSUE TITLE
Bar keeps loading

### ISSUE THREAD

**Issue by jbonet** [aitboudad/ngx-loading-bar#155]
When all my requests finish, the loading bar starts again and gets stuck forever loading.

I don't have any http request running. What can be happening? How to debug this

**Comment by aitboudad** [comment]
The loading bar shouldn't be visible when completed unless there are other pending requests,
can you provide me a reproduction example in order to investigate, here is a starter one https://stackblitz.com/edit/angular-sypacw.

Thanks!
