### ISSUE TITLE
High z-index when [fixed]="false"

### ISSUE THREAD

**Issue by maciej-laskowski** [aitboudad/ngx-loading-bar#156]
Hi,

ngx-loading-bar `div.bar` has the following styles:
```
position: absolute
z-index of 10002 
```
even when `[fixed]="false"` which means that when I use the loading bar inside my page container it is visible above modals etc. In the case of `[fixed]="false"` shouldn't the `z-index` be set to 1?

**Comment by DawnLuna** [comment]
would be nice to be able to customize z-index via input

**Comment by aitboudad** [comment]
fixed in `5.0.0-alpha.2`.

> would be nice to be able to customize z-index via input

use style: `<ngx-loading-bar [style.z-index]="100"></ngx-loading-bar>`

**Comment by maciej-laskowski** [comment]
Thanks @aitboudad !
