### ISSUE TITLE
Animation startup time

### ISSUE THREAD

**Issue by SergejSachs** [aitboudad/ngx-loading-bar#158]
Hello, it would be nice if the animation starts in a configurable time like 2 seconds.
If my route or http request is finished in that time no bar will show up.

The problem to handle this on my site was if i do mulitple requests in that 2 second window, 
not sure if its easier to handle on the lib site.

**Comment by aitboudad** [comment]
does this related to https://github.com/aitboudad/ngx-loading-bar/issues/142, if so could you please try with `5.0.0-alpha.1` version and let me know if that fixed your issue.

**Comment by SergejSachs** [comment]
It was a long time ago i wrote this code and reverteted it.
I will reimplement this and test it with the latest version but would be as well a cool option to have on the lib.

**Comment by aitboudad** [comment]
done in [v5.1.0](https://github.com/aitboudad/ngx-loading-bar/releases/tag/v5.1.0).
