### ISSUE TITLE
Bar doesn't work with Angular 10

### ISSUE THREAD

**Issue by clem4net** [aitboudad/ngx-loading-bar#163]
I upgrade my project to Angular 10 :
 - In version 4.2.0, the loading bar appears
 - In version 5.0.2, the loading bar doesn't appear

I use LoadingBarHttpClientModule.

**Comment by aitboudad** [comment]
just tested with our demo example and seems working from our side so in that case, I may need a reproduction example https://stackblitz.com/edit/angular-sypacw.

Note for `v5`, please ensure checking the mentioned breaking change in https://github.com/aitboudad/ngx-loading-bar/releases/tag/v5.0.0

**Comment by clem4net** [comment]
Thank you for the quick response (and thank you for your work, it's a great package ;))
Before I open the issue, I readed the breaking change, but I don't use internal selectors.

I try to reproduce the problem with stackblitz, but it's always worked.
So, I created a new "real" angular application from scratch and I reproduce the problem.
In the attached zip, if I use 4.2.0 version it works, but not with the 5.0.1 version.
(or I have a problem with my computer "pp)

[test.zip](https://github.com/aitboudad/ngx-loading-bar/files/4849854/test.zip)

**Comment by MrSatyam77** [comment]
I have facing same problem i try your stackblitz demo pan my side not work version 4.2.0 working but 5.0.2 not working in my project.Please give me solution

**Comment by aitboudad** [comment]
I'm able to reproduce it and looking for a fix.

**Comment by MrSatyam77** [comment]
Ok thanks

**Comment by aitboudad** [comment]
fixed in [v5.0.2](https://github.com/aitboudad/ngx-loading-bar/releases/tag/v5.0.2).

**Comment by clem4net** [comment]
Thanks for the fix, it's work :)

**Comment by MrSatyam77** [comment]
Thanks for the fix it's work also my side
