### ISSUE TITLE
ngx-loading-bar@5.0.2 forRoot() does not exist. 

### ISSUE THREAD

**Issue by FearGannicus** [aitboudad/ngx-loading-bar#165]
Hey, absolutely new to `ngx-loading-bar`. Was just trying to import and setup manually, but for some reason when following the instructions shown in your `README.md` I am running into the follwing error in my `app.module.ts` file. 

```sh
Property 'forRoot' does not exist on type 'typeof LoadingBarModule'.ts(2339)
```

Not sure if there is something i did wrong, but the steps I followed were;
1. running `npm install @ngx-loading-bar/core`
2. adding `import { LoadingBarModule } from '@ngx-loading-bar/core';` into my app.module.ts
3. in the imports section, adding the following line; `LoadingBarModule.forRoot()`

Thanks for any help in advance <3

**Comment by aitboudad** [comment]
updated Readme, just import `LoadingBarModule` without `forRoot` call:

```patch
@NgModule({
  imports: [
-   LoadingBarModule.forRoot(),
+   LoadingBarModule,
  ],
})
export class AppModule {}
```
