### ISSUE TITLE
Packages with wrong peerDependencies

### ISSUE THREAD

**Issue by Carniatto** [aitboudad/ngx-loading-bar#170]
This error is being reported by npm

![image](https://user-images.githubusercontent.com/1366831/87563921-74967e00-c6c8-11ea-854b-65e3481ed088.png)

**Comment by aitboudad** [comment]
Please ensure `@ngx-loading-bar/core` is included in your `package.json` and match the same version as `http-client` and `router` (`v5.1.0`). The `@ngx-loading-bar/http` package is not used anymore and can be removed when using `v5.1.0`.
