### ISSUE TITLE
Fade the background

### ISSUE THREAD

**Issue by docampog30** [aitboudad/ngx-loading-bar#171]
Hello 
I'm using `"@ngx-loading-bar/core": "^4.0.0"`, and `"@ngx-loading-bar/http-client": "^4.0.0"`, I want to fade or block the background while the loading bar is showing in order to prevent user actions, it's possible ?

Thanks

**Comment by aitboudad** [comment]
Target `ngx-loading-bar` selector and apply the fade using css.

**Note**: in `V5` we've improved the internal selectors to simplify adjusting the style which I suggest doing an update first.
