### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by cquirosj** [aitboudad/ngx-loading-bar#176]
Hi,

I just wanted to write to say thanks for this module. I used the old AngularJS version your project was inspired on, but I don't think its internal code and design were as beautiful as yours. 

I really liked how the core module was coded in a way that it allows programmers to create their own "progress reporters" and plug them into the core using loader.useRef('myProgressReporterPlugIn'); just like you did when you created one for Http requests and one for the router! Genius!!! I also loved how the core will take care of aggregating the progress of all "plug-ins" that are reporting progress at the same time. So good!

I think that this "plug-in" capability could be better described in the documentation and perhaps with a dedicated demo. If you allow me, I can work on such demo + improved documentation and send a PR.

Then again, thank you very much, and congratulations on your design skills.

Best regards,
Christian Q.

**Comment by aitboudad** [comment]
Hi, thanks for your kind words 👍 and happy coding!

> If you allow me, I can work on such demo + improved documentation and send a PR.

for sure!
