### ISSUE TITLE
ignoreLoadingBar in guard

### ISSUE THREAD

**Issue by viros** [aitboudad/ngx-loading-bar#179]
I'm using can deactivate guard in our app. In the guard I show confirmation popup to confirm to leave the page with unsaved data. Can't find a way to disable loading bar for this case. I can't use 'ignoreLoadingBar' with route because i want to disable it only when i show confirmation popup

**Comment by aitboudad** [comment]
can you try the following solution 🤔, inject `LoadingBarService` in your guard and hide the loading when confirmation is shown then once confirmed call `ref.start();`
```ts
const ref = this.loader.useRef('router');
ref.complete();
```

**Comment by viros** [comment]
I've tried this but it didn't work. I guess that it has in our case latency 100. So i call complete method but it seems it's starts only after delay specified in latency config

**Comment by aitboudad** [comment]
I've set an example https://stackblitz.com/edit/angular-bqbd6z and seems to work as expected.

**Comment by viros** [comment]
I was wrong. We used router module, and implemented the same logic manually in our appcomponent to handle router events. I guess it was implemented for another component we used before migrated to this component. So the problem was in our code. and now it works.
Thanks
