### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null'. Current value: '0'.

### ISSUE THREAD

**Issue by billyjov** [aitboudad/ngx-loading-bar#181]
Environment: 

- Angular 10.2.0
- ngx-loading-bar 5.1.0

![2020-11-25 13_03_01-loading-bar](https://user-images.githubusercontent.com/18737653/100225795-0f2c8680-2f1f-11eb-9a5c-aa22b662d084.png)

This appears only the first time after login into our app

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction? Thanks!

**Comment by valentin78** [comment]
have same issue, sometimes on DEV environment of course
