### ISSUE TITLE
Only have loading bar when loading lazy module

### ISSUE THREAD

**Issue by Chocobozzz** [aitboudad/ngx-loading-bar#182]
Hi and thanks for this module!

I want to display a loading bar only when the app is loading a lazy loaded module. Unfortunately `LoadingBarRouterModule` displays a loading bar every time the route changes.

Detecting a lazy route load is quite easy because the router sends a `RouteConfigLoadStart` and `RouteConfigLoadEnd` event.

**Comment by aitboudad** [comment]
Hi, instead of using the provided router module, define your own which is easy to implement:

```ts
export class AppModule {
  constructor(router: Router, loader: LoadingBarService) {
    const ref = loader.useRef('router');
    router.events.subscribe((event) => {
      if (event instanceof RouteConfigLoadStart) {
        ref.start();
      }

      if (event instanceof RouteConfigLoadEnd || event instanceof NavigationError) {
        ref.complete();
      }
    });
  }
}
```
