### ISSUE TITLE
Loading bar breaks when combined with NGXS

### ISSUE THREAD

**Issue by LuckeeDev** [aitboudad/ngx-loading-bar#184]
I'm having this issue with NGXS and this library. HTTP calls triggered by NGXS Actions make the bar start loading, but it never completes (the bar reaches 100% and doesn't disappear and the spinner keeps spinning). Manually completing the loading bar with `loadingBarService.useRef().complete()` doesn't help.

Any idea on how to solve this?

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction? 
here is a starting example https://stackblitz.com/edit/angular-sypacw

**Comment by LuckeeDev** [comment]
Here you go: https://stackblitz.com/edit/loading-bar-ngxs!
As you can see, simply dispatching an action doesn't trigger the loading bar. It kinda works when dispatching and then subscribing, but the loading bar then freezes.

**Comment by LuckeeDev** [comment]
I just forked the repo to dig more into this issue. Might open a PR if I come up with a solution :)

**Comment by aitboudad** [comment]
The issue was related to NGXS which runs actions outside of Angular Zone (https://stackoverflow.com/a/58509995/1406096), I've pushed a fix in version [v5.1.2](https://github.com/aitboudad/ngx-loading-bar/releases/tag/v5.1.2).

Thanks for the effort!

**Comment by LuckeeDev** [comment]
Thank you for the great work you're doing on this library! Works perfectly now.
