### ISSUE TITLE
NullInjectorError: No provider for e! - @ngx-loading-bar/http-client

### ISSUE THREAD

**Issue by manish-techlect** [aitboudad/ngx-loading-bar#187]
Did exactly described in readme file for @ngx-loading-bar/http-client.
Also works perfectly when 'ng serve', but get a below issue when 'ng build --prod'.
Note: The build is working fine when created by 'ng build'.

ERROR NullInjectorError: StaticInjectorError(s)[Ol -> e]: 
  StaticInjectorError(Platform: core)[Ol -> e]: 
    NullInjectorError: No provider for e!

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction? 
here is a starting example https://stackblitz.com/edit/angular-sypacw
