### ISSUE TITLE
@angular/common/http

### ISSUE THREAD

**Issue by Tolitech** [aitboudad/ngx-loading-bar#19]
Hello.
Is there any idea to work with the new angular/common/http?

Thanks.

**Comment by aitboudad** [comment]
Hi, just published a new package for HttpClient, just import `LoadingBarHttpClientModule` from  `@ngx-loading-bar/http-client`

```ts
import { LoadingBarHttpClientModule } from '@ngx-loading-bar/http-client';

@NgModule({
  ...
  imports: [
    BrowserModule,
    LoadingBarHttpClientModule,
  ],
})
export class AppModule {
}
```

**Comment by Tolitech** [comment]
Thanks for the quick feedback.
I'll test it later more calmly.
Even though I change the components, it still does not display.

I'll see what it can be.
Thank you very much.

**Comment by aitboudad** [comment]
make sure that HttpClient and LoadingBar modules is not part of your shared module see https://github.com/aitboudad/ngx-loading-bar/issues/14#issuecomment-320643714 for more details.

**Comment by Tolitech** [comment]
Sorry to disturb you.

In my project that has several modules, was already working and I just changed the old component for the new one. And it does not appear.

So I decided to create a new project, clean, and I do not know why, but it also does not appear.

At first I thought it was CSS, but the component does not change its state as it used to.

Source code:
[https://stackblitz.com/edit/angular-ezvprn](url)

App:
[https://angular-ezvprn.stackblitz.io](url)

**Comment by aitboudad** [comment]
fixed now, just update into `1.0.0-alpha.3` version, for style it seems stackblitz doesn't apply it not sure why.

**Comment by Tolitech** [comment]
This is perfect.
Now it's working.
Thank you very much.

**Comment by Tolitech** [comment]
Hello, @aitboudad .
How are you?

Was there any recent change in the library that made it stop working?

The impression I have is that the triggered services can no longer be identified.

The html tag 
<ngx-loading-bar>
<! - bindings = {
   "ng-reflect-ng-if": "false"
} ->
</ ngx-loading-bar> does not even move.

It worked perfectly until those days.
I realized today that the loading-bar had stopped being displayed.

I even tried to go back to version 1.0.0-alpha.3 that worked for me since the last change. 
But no more appeared the loading-bar.

Any changes in the version of Angular?

Thanks.

**Comment by aitboudad** [comment]
Hi, I'm good :)
Recently some deprecated methods was removed in `LoadingBarService` (only relevant if you use `LoadingBarService` see (CHANGELOG.md)[https://github.com/aitboudad/ngx-loading-bar/blob/master/CHANGELOG.md#100-alpha13-2017-10-26]) + a new [demo example](https://angular-sypacw.stackblitz.io/) which cover all existing features.
Except that I don't see any changes that may break your app.

**Comment by Tolitech** [comment]
Hi, @aitboudad .
Something has happened in version 12 that stopped loading on my system.

I ran a npm list and realized that until version 11, the library works perfectly.

Already in version 12 it stops to display the loading-bar.

To simulate, I had to delete the package-lock.json file and manually test the versions, changing to fixed versions such as "ngx-loading-bar/http-client": "1.0.0-alpha.11".

Even version 11 worked perfectly.
Then version 12 and finally version 13 no longer display the loading-bar.

What do you think it could be?

Thank you.

![image](https://user-images.githubusercontent.com/20425889/32193919-f983843a-bd9f-11e7-8857-f9730711d7d1.png)

![image](https://user-images.githubusercontent.com/20425889/32193937-055514ae-bda0-11e7-9bf1-6204a743d781.png)

![image](https://user-images.githubusercontent.com/20425889/32193947-0db2559e-bda0-11e7-9cee-35ab8501efb5.png)

**Comment by aitboudad** [comment]
I have no idea what's going wrong there and it's hard to figure out the issue without a reproduction, try to debug inside ngx-loading-bar:

1. `node_modules/@ngx-loading-bar/http-client/@ngx-loading-bar/http-client.es5.js` check if [this.loadingBar.start](https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/http-client/src/loading-bar.interceptor.ts#L23) is called
2. `node_modules/@ngx-loading-bar/core/@ngx-loading-bar/core.es5.js` check if [this.start](https://github.com/aitboudad/ngx-loading-bar/blob/master/packages/core/src/loading-bar.component.ts#L30) called too

If you can provide me a repro using https://stackblitz.com/edit/angular-sypacw it would nice!

**Comment by Tolitech** [comment]
Hello, @aitboudad. 
I got the project I have used to maintain exactly the same structure. 
I just erased everything I thought was unnecessary.

I tried to leave the code as clean as possible.
The smallest possible code.

If you download the code (angular-cli) of this link that I am passing you, you can simulate exactly the same problem.

[http://www.codegenerator.com.br/downloads/angular-cli.zip](http://www.codegenerator.com.br/downloads/angular-cli.zip)

If you keep the alpha.11 version the loading-bar will work perfectly.
If you keep the alpha.12 or alpha.13 versions the loading-bar will no longer be displayed.

Do not forget to delete the package-lock.json file when you switch from one version to another. Otherwise the package will keep the latest installed.

Thank you in advance for your attention.

![image](https://user-images.githubusercontent.com/20425889/32253165-a638d85c-be80-11e7-8c6b-a27f73369255.png)

![image](https://user-images.githubusercontent.com/20425889/32253187-c397de48-be80-11e7-8a47-e94d1cea2ee8.png)

![image](https://user-images.githubusercontent.com/20425889/32253283-2c3d75b6-be81-11e7-87a9-e100cd399212.png)

![image](https://user-images.githubusercontent.com/20425889/32253307-4f303d06-be81-11e7-8bfb-3502c07b5da3.png)

**Comment by aitboudad** [comment]
fixed in `alpha.12`

**Comment by aitboudad** [comment]
sorry in `alpha.14`

**Comment by Tolitech** [comment]
thank you so much.
