### ISSUE TITLE
Loading bar shows only after request is completed

### ISSUE THREAD

**Issue by nhack** [aitboudad/ngx-loading-bar#198]
After switching from version 4 to version 6 I have noticed that the loading bar only shows up after the HTTP request is completed and not when the request is made.

The last version where it worked was 4.2.0 I have tested with version 5.1.1, 5.1.2 and 6.0.2 and it doesn’t work. I’m using Angular 15.1.3.

app.module.ts
`
@NgModule({
  imports: [LoadingBarHttpClientModule]
})
export class AppModule{}
`

app.component.html
`
<ngx-loading-bar></ngx-loading-bar>
`

**Comment by aitboudad** [comment]
Close for missing a reproduction example.
