### ISSUE TITLE
Ionic 3 and lazy loading configuraiton example

### ISSUE THREAD

**Issue by SidMorad** [aitboudad/ngx-loading-bar#21]
First thank you for this quit up-to-date module. I am trying to make this module work with Ionic 3 (which uses Angular 4.1.3 at the moment, Note: Angular 4.3.x support will come in next release) plus it's lazy loading setup. but It seems I have to import `LoadingBarModule` in both modules(`root` and `lazy loaded one`) and after that `LoadingBarService` doesn't work as expect when is called from lazy-loaded pages. Note: `'ngx-loading-bar' is not a known element` error will throw if lazy-loaded module doesn't import `LoadingBarModule`.

Under this issue title, it will be great if someone can provide a working example for Ionic 3 and lazy loading configuration. 

Thanks!
p.s. If you have any suggestions? I will be happy to try it and see if works or not.

**Comment by aitboudad** [comment]
@SidMorad fixed in `1.0.0-alpha.8`, in `lazy` module try to import `LoadingBarModule` instead
```ts
import { LoadingBarModule } from '@ngx-loading-bar/core';
@NgModule({
    imports: [
        LoadingBarModule,
    ],
})
export class ChildModule {}
```


please try it and let me know if it's working!

**Comment by SidMorad** [comment]
@aitboudad I do confirm that version `1.0.0-alpha.8` is working for me! :tada: 

Thank you for your fast response! and also for this simple/awesome module! :smiley:

**Comment by aitboudad** [comment]
Closing for now and Thanks!
