### ISSUE TITLE
HTTP queries are executed twice

### ISSUE THREAD

**Issue by PatrykTucki** [aitboudad/ngx-loading-bar#22]
Without `ngx-loading-bar`, all HTTP requests done with Angular's `http` service are executed once.
With `ngx-loading-bar`, all HTTP requests done with Angular's `http` service are executed twice.

![bug](https://user-images.githubusercontent.com/9299202/31517036-e5eace82-af9a-11e7-9919-b6decada41aa.png)

**Comment by aitboudad** [comment]
Hi,
it would be helpful if you can provide me an example using https://stackblitz.com reproducing the issue.
Thanks!

**Comment by PatrykTucki** [comment]
Hi, I couldn't make it work on stackblitz at all. Please do

```
git clone https://github.com/PatrykTucki/ngx-loading-bar-issue
npm install
npm start
```

You'll see that two queries are made on each load.

**Comment by aitboudad** [comment]
fixed, thanks!
