### ISSUE TITLE
Add support to disable any user interactions with the application when it is loading

### ISSUE THREAD

**Issue by bhaskerchari** [aitboudad/ngx-loading-bar#3]
I think it would be great if we could also add a support to block the user interactions with the current page by adding some kind of a configurable parameter.

May be a kind of transparent overlay which by visual appearance doesn't seem to blocking but it does when user tries to interact with the page.

Thanks,
Bhasker

**Comment by ybaturin** [comment]
It is a nice idea but you really can do it by yourself.
I mean the module has LoadingBarService so this is enough for almost all stuff :)

**Comment by aitboudad** [comment]
yep that true, adding an example in the demo would be helpful for a newcomers ;)

**Comment by wwarby** [comment]
I'm about to have a go at implementing this feature myself because I need it. Once I have a workable solution I'll post it here. I'm inclined to think it should be integrated into the library itself though - it's surely something many users of this library will need.

**Comment by wwarby** [comment]
My solution:
```
TS:
import { LoadingBarService } from '@ngx-loading-bar/core';
export class AppComponent {
  constructor(public readonly loader: LoadingBarService) {}
}

HTML:
<div *ngIf="(loader.progress$|async) as progress" class="overlay"></div>

CSS:
.overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: #fff;
  opacity: 0;
  z-index: 2147483647;
}
```

Works a treat.
