### ISSUE TITLE
custom _latencyThreshold?

### ISSUE THREAD

**Issue by apunkto** [aitboudad/ngx-loading-bar#30]
Is there a reasonable way to alter _latencyThreshold? Would be nice to be able to configure it, thanks!

**Comment by aitboudad** [comment]
why would you like to update it, is there a reasonable use-case ?

**Comment by apunkto** [comment]
Maybe I'm looking at the wrong variable but what i would like to configure is the time that elapses before the loader is displayed. I have some input-suggest fields that normally react fairly quick - at the moment the loader pops up for some milli-seconds with every keystroke. I would like it to pop up only when a request has taken more than 500ms for example - enough time for not letting the user click the button twice but also enough not to pop up loader with every keystroke in the input suggest field. I hope I made myself clear :)

**Comment by aitboudad** [comment]
@apunkto can you work on this ?

**Comment by aitboudad** [comment]
I'll take care of this

**Comment by makkart** [comment]
+1

**Comment by thomas-jakemeyn** [comment]
This would indeed be a very valuable addition.

**Comment by aitboudad** [comment]
hi, here is an example:

```ts
@Component({
  selector: 'app-root',
  template: `
    <mat-progress-bar mode="determinate" 
      [value]="progress$|async">
    </mat-progress-bar>
  `,
})
export class AppComponent {
  progress$ = this.loadingService.progress$.pipe(
    delay(1000),
    withLatestFrom(this.loadingService.progress$),
    map(v => v[1]),
  );

  constructor(public loadingService: LoadingBarService) {}
```

https://stackblitz.com/edit/angular-34bv7d

**Comment by aitboudad** [comment]
added in the demo page
