### ISSUE TITLE
Can change bar color?

### ISSUE THREAD

**Issue by mic8** [aitboudad/ngx-loading-bar#37]
Is there any way to change the bar color or any custom component style?

**Comment by aitboudad** [comment]
@mic8 you can change the color by setting `color` input in `ngx-loading-bar` component:
```html
<ngx-loading-bar [color]="'red'"></ngx-loading-bar>
```
for more advanced custom style just create your own CSS to override [loading-bar.css](https://github.com/aitboudad/ngx-loading-bar/blob/master/loading-bar.css)

**Comment by mic8** [comment]
@aitboudad thank you for your quick response.

**Comment by aitboudad** [comment]
@mic8 thanks for opening this issue, let me know if there is any other relevant option we can add to simplify customization.

**Comment by mic8** [comment]
Sure I will review any customization.

**Comment by js2me** [comment]
@aitboudad sorry, but how to override default styles? Just I wanna full change style of loading bar and spinner

**Comment by aitboudad** [comment]
@js2me you can use your own loader (html + style), see how we did with [material progress-bar](https://github.com/aitboudad/ngx-loading-bar#integration-with-material-progress-bar) integration

**Comment by js2me** [comment]
@aitboudad overrided, thanks
