### ISSUE TITLE
Customize color

### ISSUE THREAD

**Issue by lexcaraig** [aitboudad/ngx-loading-bar#39]
It would be great if we can customize the color by passing the hex to the component to make it easier. :)

**Comment by aitboudad** [comment]
@lexcaraig you can change the color by setting `color` input in `ngx-loading-bar` component:
```html
<ngx-loading-bar [color]="'red'"></ngx-loading-bar>
```

**Comment by aitboudad** [comment]
updated README

**Comment by lexcaraig** [comment]
Nice, as I thought. Thanks! Really appreciate it.
