### ISSUE TITLE
Loading not closed on multiple search http request

### ISSUE THREAD

**Issue by mic8** [aitboudad/ngx-loading-bar#40]
Loading not closed when multiple http request like searching cases

![image](https://user-images.githubusercontent.com/12959448/34077830-06df0c88-e340-11e7-8660-9561461809c1.png)

**Comment by mic8** [comment]
![image](https://user-images.githubusercontent.com/12959448/34077838-29500146-e340-11e7-9de6-3cbf073ae535.png)
For multiple http request like this, I think this happen when the request not completed or have error response.

**Comment by aitboudad** [comment]
@mic8 can check `1.0.0-rc.3` if it fix your issue ?

**Comment by mic8** [comment]
Sorry for my late response, thank you @aitboudad for your response.
