### ISSUE TITLE
Infinitive loading

### ISSUE THREAD

**Issue by optimistex** [aitboudad/ngx-loading-bar#42]
After some requests the loading bar do not disappear after request is finished.

I have the version: ``"@ngx-loading-bar/http": "^1.0.0-rc.3",``

**Comment by aitboudad** [comment]
any change to provide a reproduction :) ?

**Comment by optimistex** [comment]
I had used the @ngx-loading-bar/http with the deprecated HttpModule. I was reason to the problem.
Now I did reinstall the component to @ngx-loading-bar/http-client and did change Http to HttpClient on my project.

Now the bug is disappear. 

Sorry for worrying )))
