### ISSUE TITLE
Infinite loading when using Observable.zip

### ISSUE THREAD

**Issue by goncalolucas** [aitboudad/ngx-loading-bar#43]
Merging the result of multiple http requests using Observable.zip causes the loading bar to be displayed forever. I'm using version 1.0.0. Any ideas? Thanks

**Comment by aitboudad** [comment]
@goncalolucas hi, can you tell me which package you use `http-client` or `http` ?

**Comment by goncalolucas** [comment]
Using @ngx-loading-bar/http

**Comment by goncalolucas** [comment]
Thanks

**Comment by aitboudad** [comment]
released under `1.0.1`
