### ISSUE TITLE
Loading bar doesn't fill all page width

### ISSUE THREAD

**Issue by mikehoh** [aitboudad/ngx-loading-bar#47]
I've tried three versions - httpclient, router and manual. And for all versions it works not like on your demo page. Loading bar starts to grow and stops at ~10-15% of width of the page. It can be for seconds in this position and then request finishes its work and loading bar is hiding. I've never seen loading bar reach full width.

Does someone have such behavior?

**Comment by aitboudad** [comment]
Hi, can you provide us a reproduction example ? here is a our demo to update https://stackblitz.com/edit/angular-sypacw

**Comment by mikehoh** [comment]
Sorry for delay. It was side-effect when browser is too overloaded (many tabs opened) and developer console is open. For regular user it works fine. Thanks you.
