### ISSUE TITLE
Custom loading template

### ISSUE THREAD

**Issue by makkart** [aitboudad/ngx-loading-bar#48]
Is there any plan for providing a way to specify a custom template?

Example from the AngularJs version (https://github.com/chieffancypants/angular-loading-bar)

> **Customize the template:**
> If you'd like to replace the default HTML template you can configure it by providing inline HTML as a string:

```
angular.module('myApp', ['angular-loading-bar'])
  .config(['cfpLoadingBarProvider', function(cfpLoadingBarProvider) {
    cfpLoadingBarProvider.spinnerTemplate = '<div><span class="fa fa-spinner">Loading...</div>';
  }])
```
It would be very nice to have that option, thanks.

**Comment by aitboudad** [comment]
yep why not!

**Comment by aitboudad** [comment]
@makkart instead of complicating things, I think this feature is already possible, see how we did with [material progress-bar](https://github.com/aitboudad/ngx-loading-bar#integration-with-material-progress-bar).

**Comment by makkart** [comment]
Oh yeah, I will take a look at that, thanks!
