### ISSUE TITLE
Provide a way to cancel/abort the ongoing ajax requests while showing a loading

### ISSUE THREAD

**Issue by bhaskerchari** [aitboudad/ngx-loading-bar#5]
It would be nice and can be a great to have feature if we could add a support having a close button to cancel/abort ongoing XHR requests which will come in handy for requests which will take quite some time to load the response. 

For example user want to load a historical data report for last 5 years or something which might take more time to process and return back the response and users might want to cancel that request since its taking too long.
Also we can think of many such use cases where user want to abort the requests and navigate to other view.

Hope it makes sense.

Thanks,
Bhasker

**Comment by imranmomin** [comment]
I'm not to sure, but by calling the `unsubscribe()` method of a existing http/service call and then calling the `complete()` method of the `LoadingBarService` should work

```typescript
let sub: Subscription;

ngOnDestroy(): void {
	this.sub = this.http.get("api/reports?year=5").subscribe();
}
// on cancel button event
onCancel(): void {
	if (sub) {
		this.sub.unsubscribe();
		this.loadingBarService.complete();
	}
}
```
@bhaskerchari you can give a try.
