### ISSUE TITLE
has no exported member 'LoadingBarHttpClientModule'. with @angular 5.2.2

### ISSUE THREAD

**Issue by umfaruki** [aitboudad/ngx-loading-bar#52]
it was working fine with before but right after updating my angular version to 5.0.0 i start seeing this error in app.module:

Module '"/node_modules/@ngx-loading-bar/http-client/http-client"' has no exported member 'LoadingBarHttpClientModule'.

**Comment by aitboudad** [comment]
LoadingBarHttpClientModule is located in `node_modules/@ngx-loading-bar/http-client`,
can you remove `node_modules` and run `npm install` again ?

**Comment by umfaruki** [comment]
yes i did, same error

**Comment by aitboudad** [comment]
unfortunately I'm not able to reproduce it, I'm using angular 5 and everything seems to be working without any issue if you can provide a reproduction example I would happy to help!

**Comment by umfaruki** [comment]
this is my package.json if it may help

  "private": true,
  "dependencies": {
    "@angular-devkit/core": "0.0.28",
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc.1",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ngx-loading-bar/core": "^1.1.0",
    "@ngx-loading-bar/http-client": "^1.1.0",
    "angular2-cookie": "^1.2.6",
    "bootstrap": "^4.0.0",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "moment": "^2.20.1",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toasty": "^4.0.3",
    "oidc-client": "^1.4.1",
    "primeng": "^5.2.0-rc.1",
    "rxjs": "^5.5.2",
    "webpack": "^3.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.8.5",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~9.3.0",
    "codelyzer": "~4.1.0",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.2"
  }

**Comment by aitboudad** [comment]
here is a working example using your `package.json` https://github.com/aitboudad/ngx-loading-bar-issue-52

**Comment by umfaruki** [comment]
its strange. thanks for the help, i'll try to find out what is causing issues with me

**Comment by aitboudad** [comment]
hi, can you provide me a repo where I can reproduce the issue. Thanks!

**Comment by thaoula** [comment]
actually it didn't compile non AOT

**Comment by aitboudad** [comment]
I'm going to close since it's not actionable
