### ISSUE TITLE
Loading start on routing change but complete on after getting api response.

### ISSUE THREAD

**Issue by harleenarora** [aitboudad/ngx-loading-bar#53]
Hi, I have used this package.

Now what is happening is the loader is starting on routing change but it is stopping immediately when routing changes. It does not wait for API response.

My requirement is - It should stop after getting API response.

Thanks!

**Comment by aitboudad** [comment]
you should use `LoadingBarHttpClientModule` too, in order to take account of http calls

**Comment by aitboudad** [comment]
ok can you provide me a reproduction example, use https://stackblitz.com/edit/angular-sypacw
