### ISSUE TITLE
Loading bar doesn't trigger change detection

### ISSUE THREAD

**Issue by Aali13265** [aitboudad/ngx-loading-bar#55]
In our application the loading bar often gets "stuck" after a sequence of requests, it appears to make no progress whatsoever, but in fact the request has already been completed, the progress bar just hasn't updated. Clicking anywhere on the page triggers change detection which makes the progress bar disappear.

I noticed the progress bar component is using ChangeDetectionStrategy.OnPush, which according to the angular documentation means that component rendering depends only on its inputs. That doesn't seem to be the case here since the progress variable is retrieved directly from the service rather than being set as an input?

**Comment by aitboudad** [comment]
the issue can be solved in your side by ensuring that all requests are running inside of `zone.js`, but I would agree to remove `OnPush` if it appear difficult to solve it on your side.
