### ISSUE TITLE
Loading bar only fires after HTTP request is done

### ISSUE THREAD

**Issue by emeryowa** [aitboudad/ngx-loading-bar#58]
When upgrading to the latest version (1.1.1) I noticed that the loading bar only seems to fire after the HTTP request is done.

See https://stackblitz.com/edit/angular-thsxfd

In this video you also see that when clicking the button the HTTP request is made, but no loading bar shows until the request is done. https://cl.ly/1X2W2A3H1z29

I'm using @ngx-loading-bar-http

**Comment by aitboudad** [comment]
fixed in `1.1.2`

**Comment by emeryowa** [comment]
@aitboudad Thanks for the lightning fast fix!
