### ISSUE TITLE
Error Start Projet

### ISSUE THREAD

**Issue by kamalkech** [aitboudad/ngx-loading-bar#64]
- node version = 8.9.1
- npm version = 5.5.1

Something wrong when compile libraries, cuz after run command "npm start" i get this error : 

![1 npm start 28open 29 2018-02-28 15-23-58](https://user-images.githubusercontent.com/1313428/36795689-99364576-1c9b-11e8-9181-01774780b2ff.png)

**Comment by aitboudad** [comment]
can't reproduce if on my side (using Ubuntu), can you try to update `@angular/cli` into the latest version `1.7.1` and try again.

**Comment by kamalkech** [comment]
I have already latest version:

![2 ng new ngx 28node 29 2018-02-28 17-20-44](https://user-images.githubusercontent.com/1313428/36802232-4faec37c-1cac-11e8-8454-1964ac6de262.png)

any way thank you for your quick response.

**Comment by aitboudad** [comment]
I mean on `package.json` if it doesn't work then try to update all angular libs into the latest one, I can't do anything since I can't reproduce it on my side.

**Comment by kamalkech** [comment]
no probleme i close this issue ;) .
