### ISSUE TITLE
Upgrade to Rxjs 6

### ISSUE THREAD

**Issue by FLCreative** [aitboudad/ngx-loading-bar#70]
Hello,

It is possible to upgrade to latest Rxjs in order to be compatible with Angular 6 ?

Regards

**Comment by aitboudad** [comment]
why not, wouldn't to wait until Angular 6 is released ? also I'm not sure yet if Angular provided a smooth way for rxjs upgrade

**Comment by osnoser1** [comment]
Hi, the angular team published in the changelog a migration guide for rxjs, i leave the [link](https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/preview#)

**Comment by aitboudad** [comment]
Ok thanks for the link, I'll try to see what I can do and publish a new V2.alpha version

**Comment by aitboudad** [comment]
done, just use the version `^2.0.0-alpha.0`  see the [CHANGELOG.md](https://github.com/aitboudad/ngx-loading-bar/blob/next/CHANGELOG.md)

**Comment by aitboudad** [comment]
expect a stable release once angular 6 is released.
