### ISSUE TITLE
Use with system js

### ISSUE THREAD

**Issue by boroneaionut** [aitboudad/ngx-loading-bar#72]
### OS and Version?
> Windows 10.

### Versions
Node: v8.10.0
Npm: 5.7.1
Angular: 5.2.9

### Question
How do I use the loading bar with system.js? 
Do I need to import the librarty into system.config.js file? 
And if so, how?

Thank you.

**Comment by aitboudad** [comment]
I think so, just use the umd files, something like the following json config

```json
    '@ngx-loading-bar/core': 'https://unpkg.com/@ngx-loading-bar/core@1.5.0/bundles/core.umd.js',
    '@ngx-loading-bar/http-client': 'https://unpkg.com/@ngx-loading-bar/http-client@1.5.0/bundles/http-client.umd.js',
```
