### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by nikomon** [aitboudad/ngx-loading-bar#73]
Currently I'm using color="primary" across the whole application with angular material because I have to have support for tens of different colors / brands.

I'm not much of a css guru. Should it work or is there some problem because I use .scss

Ps. My first issue I have ever created.

**Comment by aitboudad** [comment]
Hi :), 
You can use the color input to specify the desired color https://github.com/aitboudad/ngx-loading-bar#customize-ngx-loading-bar
another option is to use the material progress bar see https://github.com/aitboudad/ngx-loading-bar#integration-with-material-progress-bar

**Comment by nikomon** [comment]
We have all the colors in assets folders and scripts that run same application with different parameters for different brands.  The angular material bar is of course good but it's not automatic.

But thank you for fast and kind reply :)

**Comment by aitboudad** [comment]
> The angular material bar is of course good but it's not automatic.

you can make it automatic with this lib using `LoadingBarService`, that's mentioned in  https://github.com/aitboudad/ngx-loading-bar#integration-with-material-progress-bar 
```html
<mat-progress-bar mode="determinate" [value]="loader.progress$|async"></mat-progress-bar>
```
check the demo https://aitboudad.github.io/ngx-loading-bar/

**Comment by nikomon** [comment]
That helped and it's now working properly. Huge thanks :)
