### ISSUE TITLE
Infinit loader

### ISSUE THREAD

**Issue by shral** [aitboudad/ngx-loading-bar#74]
If the amount of start() calls and complete() calls are not the same, the loader doesn't stop [here](https://stackblitz.com/edit/angular-pnk2hs) is an example. I think the last call of complete() should close the loader.

**Comment by shral** [comment]
@aitboudad Thank you for the response! I think that would make sense if it would (be allowed to) have more loaders on the same page but since there is only one loader this behavior is confusing and tend to lead to Infinit loader. Thank you anyway for the great job.

**Comment by ermamud** [comment]
Do you at least have a method to check if the loading bar is visible or not at the moment? I don't want to add a second instance if it is already loading.

Thank you

**Comment by aitboudad** [comment]
with `2.1.0` you can use `stop` method to force closing the loader instead of `complete`.
