### ISSUE TITLE
IncludeSpinner set to false, but spinner still showing.

### ISSUE THREAD

**Issue by amit996** [aitboudad/ngx-loading-bar#75]
`<ngx-loading-bar includeSpinner="false" height="5px" color= '#f00'></ngx-loading-bar>`
But spinner is still showing
using import { LoadingBarRouterModule } from '@ngx-loading-bar/router';

**Comment by aitboudad** [comment]
hi, can you try with:
```patch
- includeSpinner="false"
+ [includeSpinner]="false"
```

**Comment by amit996** [comment]
Thanks, Its working now.
