### ISSUE TITLE
Can't build to AOT mode for Angular 4

### ISSUE THREAD

**Issue by syiwawahyu** [aitboudad/ngx-loading-bar#76]
Hi,

This thirdparty is pretty good and really useful. But, I face a problem when build the project to AOT mode. It showing like below error.
`ERROR in Metadata version mismatch for module /var/www/html/test-project/node_modules/@ngx-loading-bar/core/ngx-loading-bar-core.d.ts, found version 4, expected 3
`
It's work normally on development mode. The error just appear when I try to build it as AOT mode production.

Can you give me any advice or help? 

Thank you very much before.

**Comment by aitboudad** [comment]
which version you use ?

**Comment by aitboudad** [comment]
ok I see what's happening I published the v2 version with latest tag, try to update the package constraints into `^1.5.1` and then followed by `npm install`.

**Comment by syiwawahyu** [comment]
Sorry for long response. But your solution is accurate. It works now. Thank you.
