### ISSUE TITLE
how to make custom template for spinner?

### ISSUE THREAD

**Issue by MinaMagdyBoshra** [aitboudad/ngx-loading-bar#79]

**Comment by aitboudad** [comment]
see https://github.com/aitboudad/ngx-loading-bar/issues/48#issuecomment-357264799

**Comment by bharat-dpd** [comment]
Can you please share an example? I would like to add the backdrop feature? so is there any way to enable backdrop view so the user can't click on the view.

**Comment by aitboudad** [comment]
check the material example https://github.com/aitboudad/ngx-loading-bar#integration-with-material-progress-bar
