### ISSUE TITLE
Missing autocomplete for ngx-loading-bar component in PhpStorm

### ISSUE THREAD

**Issue by gremo** [aitboudad/ngx-loading-bar#81]
I'm very new to Angular, this library is awesome but I'm having a minor issues with PhpStorm and autocomplete. In my `app.module.ts` I've added the following:

```
import { LoadingBarModule } from '@ngx-loading-bar/core';
import { LoadingBarHttpClientModule } from '@ngx-loading-bar/http-client';
import { LoadingBarRouterModule } from '@ngx-loading-bar/router';

// ...
@NgModule({
  imports: [
    // ...
    LoadingBarHttpClientModule,
    LoadingBarRouterModule,
    LoadingBarModule.forRoot()
  ],
// ...
```

For some reason autocomplete isn't working in PhpStorm 2018.1:

![image](https://user-images.githubusercontent.com/1532616/39409079-fb19e396-4be0-11e8-9750-a800bc603678.png)

Is there somthing wrong with my setup? Thanks!

**Comment by aitboudad** [comment]
which version you use ?

**Comment by gremo** [comment]
@aitboudad ok maybe I found the issue. I was not interested in using the "manual loading bar" so I forgot to install:

`npm install @ngx-loading-bar/core --save`

That is, if you only do the following:

```
npm install @ngx-loading-bar/http-client --save
npm install @ngx-loading-bar/router --save
```
... you end up with a working loading bar but without autocomplete.

**Comment by aitboudad** [comment]
probably an issue in `PhpStorm` since it's working in `vscode`.

**Comment by trumbitta** [comment]
I just had the same issue with vscode and fixed it by installing (but not importin) also the core package
