### ISSUE TITLE
LoadingBarHttpModule problem with lazy loading

### ISSUE THREAD

**Issue by hadirsa** [aitboudad/ngx-loading-bar#83]
I use `ngx-loading-bar` in our project. We use lazy loading. `LoadingBarRouterModule` works fine on routes changes but nothing happens on `http` request with LoadingBarHttpModule. 

We use:
 angular/http
 angular 4.3

Is there any thing  that i can do to resolve  this problem?

**Comment by aitboudad** [comment]
just ensure that `LoadingBarHttpModule` is added only in the root module not shared one
