### ISSUE TITLE
Not compatible with Angular 6

### ISSUE THREAD

**Issue by YoannBureau** [aitboudad/ngx-loading-bar#88]
Can you please make the lib Angular 6 compliant? :)

Here is a blitz example: https://stackblitz.com/edit/ngx-loading-bar-angular-6?file=src/app/app.module.ts

**Comment by aitboudad** [comment]
maybe an issue in angular, just update into `6.0.4` and it should work see https://stackblitz.com/edit/ngx-loading-bar-angular-6-bpne9j
