### ISSUE TITLE
Unable to use LoadingBarRouterModule and LoadingBarHttpClientModule together

### ISSUE THREAD

**Issue by olufemioyedepo** [aitboudad/ngx-loading-bar#89]
I've imported LoadingBarRouterModule and LoadingBarHttpClientModule into my app module but I got this error:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: LoadingBarComponent,LoadingBarComponent ("[ERROR ->]<ngx-loading-bar></ngx-loading-bar>

Please help!!!

**Comment by aitboudad** [comment]
just ensure both packages match the same version.

**Comment by aitboudad** [comment]
I'm not able to reproduce it, if you can provide me a reproduction repo it may help.
you try to run `npm install` after removing `node_modules`.

**Comment by zMADCATz** [comment]
I'm got ploblem and I try to remove `packang-lock.json` file and `node_modules` folder

and run `npm install` It's fine.
