### ISSUE TITLE
diameter and height is ignored

### ISSUE THREAD

**Issue by hkosmidi** [aitboudad/ngx-loading-bar#92]
Hello,
I am using this super library to show an indicator when angular is loading data from httClient request.
I have in app.component.html
<ngx-loading-bar [diameter]="400" [height]="100" [color]="loadingBarColor"></ngx-loading-bar>
(I put so big values just to make sure I see the differences)

but the loading bar and spinner is always the same size. Am I doing something wrong?

**Comment by aitboudad** [comment]
you should pass a valid css value for example `[diameter]="'14px'"`
