### ISSUE TITLE
Loading bar not working with ngx-restangular

### ISSUE THREAD

**Issue by dericatienza** [aitboudad/ngx-loading-bar#96]
I'm trying to use ngx-loading bar with ngx-restangular. Although I've imported both ngx-loading-bar/http and ngx-loading-bar/http-client both on the main app.module.ts the loading bar still doesn't show for all calls made through restangular. However, it does show for regular HttpClient requests.

My package summary:

"@ngx-loading-bar/core": "^2.1.0"
"@ngx-loading-bar/http": "^2.1.0"
"@ngx-loading-bar/http-client": "^2.1.0"
"@ngx-loading-bar/router": "^2.1.0"
"ngx-restangular": "^3.0.0"

Loading bar also shows for router changes.

**Comment by aitboudad** [comment]
`ngx-restangular` doesn't rely on HttpInterceptor (see https://github.com/2muchcoffeecom/ngx-restangular/issues/95),

in that case you have to manage through `RestangularConfigFactory` by relying on restangular interceptors:

```ts
import { RestangularModule, Restangular } from 'ngx-restangular';
import { LoadingBarModule, LoadingBarService } from '@ngx-loading-bar/core';

export function RestangularConfigFactory(RestangularProvider, loader: LoadingBarService) {
  ...
  RestangularProvider.addFullRequestInterceptor(() => loader.start());
  RestangularProvider.addErrorInterceptor(() => loader.complete());
  RestangularProvider.addResponseInterceptor((data) => {
    loader.complete();
    return data || {};
  });
}

@NgModule({
  imports: [
    ...
    LoadingBarModule,
    // Importing RestangularModule and making default configs for restanglar
    RestangularModule.forRoot([LoadingBarService], RestangularConfigFactory),
  ],
})
export class AppModule {}
```

**Note**: you can remove `@ngx-loading-bar/http` and `@ngx-loading-bar/http-client` if you don't use a direct http call.
